### ISSUE TITLE
ValueError: invalid literal for int() with base 10: '{list_.id}'

### ISSUE THREAD

**Issue by ceburns111** [ceburns111/list2mp3#22]
ERROR: test_redirects_after_POST (lists.tests.NewListTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/cburns/projects/list2mp3/superlists/lists/tests.py", line 47, in test_redirects_after_POST
    self.assertRedirects(response, f'/lists/{new_list.id}/')
  File "/usr/local/lib/python3.6/dist-packages/django/test/testcases.py", line 306, in assertRedirects
    redirect_response = response.client.get(path, QueryDict(query), secure=(scheme == 'https'))
  File "/usr/local/lib/python3.6/dist-packages/django/test/client.py", line 529, in get
    **extra)
  File "/usr/local/lib/python3.6/dist-packages/django/test/client.py", line 333, in get
    return self.generic('GET', path, secure=secure, **r)
  File "/usr/local/lib/python3.6/dist-packages/django/test/client.py", line 409, in generic
    return self.request(**r)
  File "/usr/local/lib/python3.6/dist-packages/django/test/client.py", line 494, in request
    six.reraise(*exc_info)
  File "/usr/local/lib/python3.6/dist-packages/django/utils/six.py", line 686, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.6/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.6/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/cburns/projects/list2mp3/superlists/lists/views.py", line 13, in view_list
    list_ = List.objects.get(id=list_id)
  File "/usr/local/lib/python3.6/dist-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/django/db/models/query.py", line 376, in get
    clone = self.filter(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/django/db/models/query.py", line 796, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/django/db/models/query.py", line 814, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "/usr/local/lib/python3.6/dist-packages/django/db/models/sql/query.py", line 1227, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/usr/local/lib/python3.6/dist-packages/django/db/models/sql/query.py", line 1253, in _add_q
    allow_joins=allow_joins, split_subq=split_subq,
  File "/usr/local/lib/python3.6/dist-packages/django/db/models/sql/query.py", line 1187, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "/usr/local/lib/python3.6/dist-packages/django/db/models/sql/query.py", line 1083, in build_lookup
    return final_lookup(lhs, rhs)
  File "/usr/local/lib/python3.6/dist-packages/django/db/models/lookups.py", line 19, in __init__
    self.rhs = self.get_prep_lookup()
  File "/usr/local/lib/python3.6/dist-packages/django/db/models/lookups.py", line 59, in get_prep_lookup
    return self.lhs.output_field.get_prep_value(self.rhs)
  File "/usr/local/lib/python3.6/dist-packages/django/db/models/fields/__init__.py", line 946, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: '{list_.id}'

Cant figure out why this is only an issue for this test and not the other three that I have in my unit tests (superlists/lists/tests)

**Comment by ceburns111** [comment]
This is using Python 3.6.1 and Django 1.10.5...i should probably set up a VM for this :(

**Comment by ddelnano** [comment]
The vm already has python installed you just need to update the version. It also might be installed already as python3. Can you change what interpreter Django is using to use python3 instead of python?
